[2019-04-12 16:20:34,842] - mod_config.py - [Line:28] - [WARNING] - No section: 'excel'
[2019-04-12 16:20:34,842] - mod_config.py - [Line:16] - [WARNING] - No section: 'excel'
[2019-04-12 16:20:35,079] - mod_config.py - [Line:28] - [WARNING] - No section: 'excel'
[2019-04-12 16:20:35,079] - mod_config.py - [Line:28] - [WARNING] - No section: 'database'
[2019-04-12 16:20:35,079] - mod_config.py - [Line:28] - [WARNING] - No section: 'database'
[2019-04-12 16:20:35,079] - mod_config.py - [Line:28] - [WARNING] - No section: 'database'
[2019-04-12 16:20:35,079] - mod_config.py - [Line:28] - [WARNING] - No section: 'database'
[2019-04-12 16:20:35,079] - mod_config.py - [Line:28] - [WARNING] - No section: 'database'
[2019-04-12 16:20:35,080] - mod_config.py - [Line:28] - [WARNING] - No section: 'database'
[2019-04-12 16:20:35,080] - mod_config.py - [Line:28] - [WARNING] - No section: 'excel'
[2019-04-12 16:20:35,080] - mod_db.py - [Line:43] - [ERROR] - connect database failed,'Database' object has no attribute '_dbhost'
